[package]
name = "four4"
version = "0.1.0"
authors = ["Aleksander Vognild Burkow <aleksanderburkow@gmail.com>"]

[dependencies]
vulkano = "0.7.1"
vulkano-shader-derive = "0.7"
vulkano-win = "0.7"
cgmath = "0.14.1"
image = "0.14.0"
winit = "0.7.0"
time = "0.1.37"
